# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_clips'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ipaddress',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clips',
            name='photos',
            field=models.ImageField(default='clips/cmu.png', upload_to='clips/%Y/%m', verbose_name='avatar'),
        ),
    ]
