# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20171107_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clips',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
